# Wprowadzenie {#sec-wprowadzenie}

<!--
Wprowadzenie powinno mieć charakter opisu od ogółu do szczegółu (np. trzy-pięć paragrafów).
Pierwszy paragraf powinien być najbardziej ogólny, a kolejne powinny przybliżać czytelnika do problemu.
Przedostatni paragraf powinien określić jaki jest problem (są problemy), który praca ma rozwiązać i dlaczego jest to (są one) ważne.

Wprowadzenie powinno być zakończone stwierdzeniem celu pracy.
Dodatkowo tutaj może znaleźć się również krótki opis co zostało zrealizowane w pracy.
-->
<!--

Wykorzystanie odnawialnych źródeł energii jako alternatywy dla źródeł kopalnych jest jednym
z priorytetów w kontekście zachodzących zmian klimatu. 

3
Uwarunkowania prawne
Europejski Zielony Ład (European Green Deal)
inicjatywy chodzi „Gotowi na 55” (Fit For 55)

Po renegocjacji ustaleń Rady UE, Parlamentu Europejskiego oraz Komisji Europejskiej w Unii
Europejskiej w 2030 roku udział odnawialnych źródeł energii w miksie energetycznym ma
wynosić 42,5%. Ze względu na fakt, iż koszt instalacji fotowoltaicznych spada przy
jednoczesnym dynamicznym wzroście ilości mocy zainstalowanej, jest to źródło energii
elektrycznej o ogromnym wpływie na ostateczny wynik starań i na transformację energetyczną
jako taką.
Podstawą polityki unijnej w aspekcie rolnictwa oraz klimatu jest Europejski Zielony Ład –
pakiet inicjatyw politycznych mających na celu osiągnięcie przez UE neutralności klimatycznej
do 2050 r. Został zainicjowany przez Komisję Europejską w grudniu 2019 roku. Do inicjatyw tych należy „Fit For 55”, stanowiący propozycje zmian przepisów związanych z klimatem,
energetyką i transportem, czy też rozporządzenie o europejskim prawie klimatycznym, które
zmienia zobowiązanie do zmniejszenia emisji gazów cieplarnianych netto o co najmniej 55%
do 2030 r. oraz do osiągnięcia neutralności klimatycznej do 2050 r. w prawnie wiążące.
Ponadto, pakiet inicjatyw uzupełnia strategia UE w zakresie przystosowania się do zmiany
klimatu, strategia na rzecz bioróżnorodności 2030, strategia „od pola do stołu”, europejska
strategia przemysłowa i wiele innych. 
REPowerEU to plan zaprezentowany przez Komisję Europejską w maju 2022 roku, identyfikujący inwestycje w OZE jako leżące w nadrzędnym interesie publicznym. Głównym motywem planu jest uniezależnienie się od importu paliw kopalnych z Rosji. REPowerEU zakłada prawie 600 GW mocy nowych paneli fotowoltaicznych zainstalowanych w Unii Europejskiej do 2030 roku. Dodatkowo, Komisja Europejska w tegorocznym komunikacie „Strategia UE na rzecz energii słonecznej” zauważa
potencjał połączenia rolniczego wykorzystania gruntów z wytwarzaniem energii z fotowoltaiki. 


4
dlaczego należy prowadzić statystykę oze?
czy można to robić na podstawie danych teledetekcyjnych?
czy na ich podstawie jest możliwe śledzenie rozwoju energetyki odnawialnej (rozwoj energetyki pochodzącej z farm fotowoltaicznych)?

Transformacja energetyczna jest procesem bardzo dynamicznym, którego monitorowanie ma istotny wpływ na rozwój kolejnych projektów dotyczących energetyki niekonwencjonalnej.

Odnawialne źródła energii towarzyszą ludziom od początku dziejów. Energię wiatru uży‐
wano do napędzania łodzi czy spalanie biomasy jako źródło ciepła. Nasilające się zmiany kli‐
matyczne wymusiły na rządach przyspieszenie dążenia do neutralności klimatycznej. Również
Polska zdeklarowała się znacząco zwiększyć udział energii ze źródeł odnawialnych, dążąc do
neutralności klimatycznej w 2050 roku.
Osiągnięcie powyższych celów będzie jedynie możliwe w momencie dokładnego monitoro‐
wania wyników oraz posiadania najaktualniejszych informacji dotyczących odnawialnych źródeł
energii. 

Jednakże, aby ten cel osiągnąć istotne jest monitorowanie oraz posiadanie aktualnych źródeł danych w zakresie wykorzystania odnawialnych źródeł energii.

5 
badania które już to robiły
Globalna baza danych elektrowni (*Global Power Plant Database*) [@globalpowerplantdb_2021], stworzona przez Byersa et al. [-@byers_2018_globalpowerplantdb] i udostępniona w czerwcu 2021 roku, wskazuje na istnienie zaledwie x elektrowni fotowoltaicznych w całej Polsce na wspomniany okres.
Ujednolicone globalne zbiory danych dotyczące lokalizacji farm wiatrowych i słonecznych oraz mocy produkowanej (*Harmonised global datasets of wind and solar farm locations and power*), opracowane na podstawie danych OpenStreetMap przez Dunnetta et al. [-@dunnet_2020_wind_solar], sugerują, że do końca roku 2018 na obszarze badania występowało jedynie x instalacji fotowoltaicznych, które zajmowały powierzchnię x hektarów.
Istnieje również jeden zbiór danych, którego sposób stworzenia był najbardziej zbliżony do omawianego w niniejszym badaniu.

@kruitwagen_2021_pv, wykorzystując zdjęcia satelitarne SPOT-6/7 i Sentinel-2 w połączeniu z metodami uczenia maszynowego, wskazał istniejące konstrukcje fotowoltaiczne na świecie na dzień 30 września 2018 roku.

w poprzednich badaniach dotyczących detekcji farm fotowoltaicznych na podstawie danych teledetekcyjnych przez Zhanga et al. [-@zhang_2021_texture], Plakmana et al. [-@plakman_2022_pv], Wanga et al. [-@wang_2022_pv] i innych, takie jak:

6
cel pracy
Praca inżynierska podejmuje się określenia optymalnych metod uczenia maszynowego do wykrywania farm fotowoltaicznych na podstawie danych teledetekcyjnych
-->

Ludzie od zawsze dążyli do wykorzystywania dostępnych źródeł energii w celu zaspokojenia różnorodnych potrzeb.
Energia odgrywa przez to kluczową rolę w naszym życiu, stanowiąc podstawę funkcjonowania społeczeństwa i napędzając rozwój gospodarczy.
Istnieje wiele metod pozyskiwania energii elektrycznej, włączając w to tradycyjne, konwencjonalne sposoby oparte na spalaniu paliw kopalnych, a także energię atomową oraz odnawialne źródła energii.
Zielona energia, inaczej określana jako odnawialne źródła energii, wykorzystuje naturalne procesy, takie jak słońce, wiatr czy ciepło wnętrza Ziemi, co czyni ją nieograniczonym źródłem energii.

Każdy, kto rozpatruje perspektywę produkcji energii, zdaje sobie sprawę, że zasoby surowców wykorzystywanych do produkcji energii konwencjonalnej są ograniczone.
Dodatkowo, rosnące zainteresowanie ochroną środowiska i negatywnymi zmianami klimatu oraz wprowadzane przepisy prawne zobowiązują do podejmowania działań mających na celu ograniczenie emisji szkodliwych gazów do atmosfery.
W obliczu globalnych zmian klimatycznych i kryzysu energetycznego, spowodowanego inwazją Rosji na Ukrainę w 2022 roku, społeczeństwo jest zmuszone do przejścia z produkcji energii opartej na paliwach kopalnych na rzecz odnawialnych źródeł energii i energetyki jądrowej.

Podstawą polityki Unii Europejskiej w obszarze klimatu jest Europejski Zielony Ład (ang. *European Green Deal*), czyli zestaw inicjatyw politycznych mających na celu przeprowadzenie transformacji ekologicznej i osiągnięcie neutralności klimatycznej w UE do 2050 roku.
Inicjatywy takie jak Gotowi na 55 (ang. *Fit For 55*) oraz rozporządzenie o europejskim prawie klimatycznym mają zapewnić redukcję emisji gazów cieplarnianych netto o co najmniej 55% do 2030 roku.
Zgodnie z ustaleniami Rady UE, Parlamentu Europejskiego oraz Komisji Europejskiej, udział energii odnawialnej w ogólnym zużyciu energii w Unii Europejskiej ma wynosić 42,5% do 2030 roku.
Plan REPowerEU, przedstawiony przez Komisję Europejską w maju 2022 roku, skupia się natomiast na inwestycjach w odnawialne źródła energii, uznając je za leżące w nadrzędnym interesie publicznym.
Celem tego planu jest zmniejszenie zależności UE od importu paliw kopalnych z Rosji poprzez zainstalowanie niemal 600 GW mocy nowych paneli fotowoltaicznych w całej Unii Europejskiej do 2030 roku.
Ambitne cele klimatyczne Unii Europejskiej, w połączeniu z równoczesnym obniżeniem kosztów instalacji fotowoltaicznych sprawiają, że energia elektryczna pochodząca z tego źródła prawdopodobnie zacznie odgrywać kluczową rolę w procesie transformacji energetycznej Unii Europejskiej.

- dlaczego należy prowadzić statystykę rozwoju OZE? dlaczego monitorowanie tego zjawiska jest tak istotne?
- krótkie omówienie badań które już to robiły
- cel pracy
