---
editor: 
  markdown: 
    wrap: sentence
---

# Materiały {#sec-materialy}

## Zdjęcia satelitarne {#sec-satellite-imagery}

### Sentinel-1 {#sec-sentinel1}

Misja Sentinel-1 stanowi Europejskie Obserwatorium Radarowe działające w ramach programu Copernicus, wspólnej inicjatywy Komisji Europejskiej i Europejskiej Agencji Kosmicznej [@sentinel1_overview].
Celem misji jest dostarczanie danych radarowych obejmujących globalną powierzchnię Ziemi, w tym lądów, europejskich stref przybrzeżnych, tras żeglugowych, stref lodu morskiego, mórz i oceanów [@hejmanowska_2020_dane; @sentinel1_mission_objectives].
Misja odpowiada na potrzeby monitorowania obszarów morskich i lądowych, w tym przemieszczania lodu morskiego, transportu morskiego, deformacji i przemieszczeń terenu, a także obserwacji zmian klimatu i klęsk żywiołowych [@hejmanowska_2020_dane; @sentinel1_mission_objectives].

Sentinel-1 jest wyposażony w radar z syntetyczną aperturą (ang. *Synthetic Aperture Radar*, SAR), pracujący w paśmie C na częstotliwości 5,405 GHz, co odpowiada długości fali 5,6 cm [@sentinel1_lulc; @sentinel1_instrument_payload].
Radar działa głównie w trybie podwójnej polaryzacji, emitując fale pionowe i mierząc zarówno fale pionowe (ang. *vertical*), jak i poziome (ang. *horizontal*) po ich powrocie do czujnika, dzięki czemu otrzymujemy dane o intensywności rozproszenia wstecznego VV i VH [@sentinel1_lulc].
Radar z syntetyczną aperturą (SAR) umożliwia prowadzenie obserwacji zarówno w nocy, jak i w dzień, niezależnie od warunków pogodowych, przez co czas między rejestracją obrazów dla pojedynczego satelity Sentinel-1 wynosi 12 dni nad równikiem, a dla konstelacji dwóch satelitów skraca się do od dwóch do sześciu dni, zależnie od szerokości geograficznej [@hejmanowska_2020_dane; @sentinel1_overview].

Dane radarowe Sentinel-1 sa dostępne na trzech poziomach przetworzenia.
Produkty poziomu 1 (Single Look Complex (SLC) i Ground Range Detected (GRD)), są przeznaczone dla użytkowników końcowych i nadają się, w zależności od produktu do do monitorowania Ziemi, klasyfikacji pokrycia terenu czy aplikacji interferometrycznych [@hejmanowska_2020_dane].
SLC to obrazy SAR w geometrii ukośnej, zachowujące informację fazową sygnału [@hejmanowska_2020_dane]. 
Produkty GRD są rezultatem przepróbkowania obrazów SLC do jednolitej rozdzielczości przestrzennej (10 × 10 m) i rzutowania na powierzchnię elipsoidy odniesienia [@hejmanowska_2020_dane]. 
GRD nie zawiera cech ortofotomapy i wymaga dodatkowego przepróbkowania z użyciem numerycznego modelu terenu przed zastosowaniem w systemach GIS [@hejmanowska_2020_dane].
Przy konwersji SLC do GRD tracimy informację fazową sygnału, co sprawia, że produkty GRD nie są odpowiednie do interferometrii radarowej [@sentinel1_products].

Dane Sentinel-1 rejestrowane są w czterech trybach: Interferometric Wide Swath (IW) – podstawowy tryb obrazowania dla obszarów lądowych, Stripmap (SM) – używany do obrazowania małych wysp i na potrzeby zarządzania kryzysowego, Extra-Wide Swath (EW) – tryb do monitorowania stref polarnych i niektórych obszarów morskich, Wave (WV) – tryb obrazowania oceanów [@hejmanowska_2020_dane; @sentinel1_instrument_payload; @sentinel1_stripmap].

Dane wykorzystane do analizy pochodzą z produktów Ground Range Detected (GRD) zarejestrowanych w trybie Interferometric Wide Swath (IW) przez satelitę Sentinel-1B w dniu 8 maja 2023 roku. Zestaw danych został utworzony poprzez połączenie dwóch sąsiednich produktów Sentinel-1 GRD, a następnie ograniczenie obszaru analizy do kafla Sentinel-2 o oznaczeniu 33UWV. W analizie uwzględniono dwie polaryzacje: VV i VH.

### Senitnel-2 {#sec-sentinel2}

Misja Sentinel-2 stanowi inicjatywę Komisji Europejskiej, która jest operacyjnie prowadzona przez Europejską Agencję Kosmiczną (ang. *European Space Agency*, ESA) w ramach programu Copernicus.
Celem tej misji jest dostarczanie obrazów satelitarnych, obejmujących trzynaście zakresów spektralnych o różnych rozdzielczościach przestrzennych: 10, 20 lub 60 metrów, zależnie od rejestrowanego kanału.
Rozdzielczość czasowa misji Sentinel-2 wynosi pięć dni nad równikiem i zwiększa się wraz ze wzrostem szerokości geograficznej, osiągając dwa dni na średnich szerokościach geograficznych [@hejmanowska_2020_dane].

Dane pozyskiwane przez satelity Sentinel-2 są dostępne na różnych poziomach przetworzenia, lecz najczęściej używane przy tworzeniu map pokrycia terenu i użytkowania ziemi (ang. *Land Use/Land Cover*, LULC) są produkty 1C (współczynnik odbicia na poziomie górnej części atmosfery; ang. *Top-of-Atmospheric reflectance*, TOA) oraz 2A (współczynnik odbicia na powierzchni Ziemi; ang. *Bottom-of-Atmospheric reflectance*, BOA) [@phiri_2020_sentinel2].

Produkty poziomu 1C to dane poddane korekcjom radiometrycznym i geometrycznym, prezentowane jako sceny o powierzchni 100 km^2^ (100 x 100 km) w projekcji UTM/WGS84 [@esa_2015_sentinel2handbook].
Skuteczne wykorzystanie tych danych w zastosowaniach związanych z terenami lądowymi wymaga precyzyjnej korekcji zdjęć satelitarnych pod kątem efektów atmosferycznych [@main-knorn_2017_Sen2Cor].
Produkty poziomu 2A powstają poprzez zastosowanie dodatkowej korekcji atmosferycznej dla danych poziomu 1C za pomocą procesora korekcji atmosferycznej Sen2Cor [@main-knorn_2017_Sen2Cor].

```{r tabela1, echo=FALSE}
#| label: tbl-tabela1
#| echo: false
#| tbl-cap: "Kanały spektralne satelitów Sentinel-2"
df = data.frame(
  a = c("B01","B02","B03","B04","B05","B06","B07","B08","B8A","B09","B10","B11","B12"),
  b = c("Coastal Aerosol","Blue","Green","Red","Vegetation RedEdge","Vegetation RedEdge","Vegetation RedEdge","NIR","NIR","Water Vapour","Cirrus","SWIR","SWIR"),
  c = c(443,490,560,665,705,740,783,842,865,945,1375,1610,2190),
  d = c("433–453","458–523","543–578","650–680","698–713","733–748","773–793","785–900","855–875","935–955","1360–1390","1565–1655","2100–2280"),
  e = c(60,10,10,10,20,20,20,10,20,60,60,20,20)
)
colnames(df) = c("Kanał", "Nazwa kanału", "Centralna długość fali [nm]", "Zakres spektralny [nm]", "Rozdzielczość przestrzenna [m]")
knitr::kable(df, booktabs = TRUE) |> 
  kableExtra::column_spec(1, width = "1.5cm") |>  
  kableExtra::column_spec(2, width = "4cm") |>
  kableExtra::column_spec(3, width = "2cm") |> 
  kableExtra::column_spec(4, width = "2cm") |> 
  kableExtra::column_spec(5, width = "2cm")
```

Dane wykorzystane w analizie pochodzą z dnia 8 maja 2023 roku i zostały dostarczone przez satelitę Sentinel-2B.
Obszar analizy obejmuje kafel (ang. *tile*) o oznaczeniu 33UWV, dla którego współczynnik zachmurzenia w tym dniu wynosił 0,7%.
Użyte zostały dane na poziomie przetworzenia L2A.
Z dostępnych kanałów spektralnych (Tabela [-@tbl-tabela1]) wykorzystano 10 zakresów, ponieważ pasma rejestrowane w rozdzielczości 60 metrów są przeznaczone głównie do korekcji atmosferycznych i detekcji chmur. Kanał 1 (443 nm) służy do korekcji wpływu aerozoli, kanał 9 (940 nm) do korekcji wpływu pary wodnej, a kanał 10 (1375 nm) do wykrywania chmur typu cirrus [@drusch_2012_sen2GMES].

### Indeksy spektralne

### Tekstury obrazu

## Ortofotomapa i mozaiki zdjęć satelitarnych {#sec-mosaics}

Do lokalizacji oraz wektoryzacji istniejących farm fotowoltaicznych wykorzystano ortofotomapę udostępnianą przez Główny Urząd Geodezji i Kartografii oraz mozaiki zdjęć satelitarnych dostarczane przez podmioty komercyjne.
W teledetekcji jednym z zastosowań mozaik obrazów satelitarnych jest tworzenie zestawów danych referencyjnych poprzez interpretację wizualną, np. w celu walidacji wyników klasyfikacji produktów pokrycia terenu [@lesiv_2018_sat_imagery_mosaics]. 
Do stworzenie zbioru danych testowych i treningowych wykorzystano ortomozaiki Google Satellite, Bing Aerial, Mapbox Satellite oraz Planet Basemaps, udostępniane w formie usług sieciowych (WMS, WMTS, XYZ Tiles).
Ortomozaiki te są tworzone na podstawie komercyjnych zdjęć satelitarnych wykonywanych przez podmioty takie jak Maxar Technologies, Airbus czy Planet Labs.
Ortofotomapa udostępniana przez GUGiK charakteryzuje się rozdzielczością przestrzenną 25 cm, a rozdzielczość przestrzenna wykorzystanych mozaik obrazów satelitarnych (poza Planet Basemaps) jest wyższa niż 1 m, np. dla mozaiki Bing Aerial udostępnianej przez firmę Microsoft wynosi ona 30-60 cm.
Często jednak nie jest możliwie ustalenie dat wykonania zdjęć satelitarnych, które posłużyły do stworzenia konkretnej mozaiki zobrazowań satelitarnych [@lesiv_2018_sat_imagery_mosaics]. 
Mozaika tworzona przez Planet na podstawie zdjęć satelitarnych wykonywanych przez konstelację satelitów PlanetScope charakteryzuje się rozdzielczością przestrzenną 4,77 m na równiku, jednak w porównaniu do pozostałych wymienionych produktów jest tworzona z miesięczną oraz kwartalną częstotliwością. Pozwala to, pomimo niższej rozdzielczości przestrzennej na stworzenie zbioru danych testowych i treningowych na konkretny okres czasu [@planet_2019_basemaps].
Mozaiki Planet Basemaps są tworzone na podstawie zdjęć wybieranych przy użyciu algorytmu, który wybiera najlepsze obrazy z katalogu Planet w określonym przedziale czasowym. Wybierając najlepsze obrazy, Planet jest w stanie tworzyć wysokorodzielcze mozaiki, które są dokładne radiometrycznie i przestrzennie, a także charakteryzują się zminimalizowanym wpływem czynników atmosferycznych [@planet_2019_basemaps].

?Rycina przedstawiająca jedną farmę na ortofotomapie, mozaikach satelitarnych i scenie Sentinel-2 (kompozycja RGB)
